Child details page
fokus-team/fokus pull request #32
Opened 2020-08-28 13:02 UTC by mikolajmirko

2020-08-28 13:09 UTC, mikolajmirko commented
I updated the AppPage enum listing - I don't want to resolve conflicts in here for 10th time ;_;
![code](https://user-images.githubusercontent.com/36575365/91564100-629f3080-e940-11ea-9639-1dc9ba1280cc.png)

2020-08-28 13:19 UTC, mikolajmirko commented
Updated merge request description with summary.

2020-08-29 10:40 UTC, stasgora requested changes

2020-08-29 10:40 UTC, stasgora commented on i18n/en_US.json
> +					"noachievementsText": "No awarded badges to display",
Typo, the 'a' should be capital

2020-08-29 10:40 UTC, stasgora commented on i18n/en_US.json
> +						"noAwardsAdded": "The list of awards available for purchase is empty. Add an award for a child to earn.",
for a child to **claim**, maybe?

2020-08-29 10:40 UTC, stasgora commented on lib/pages/caregiver/child_dashboard_page.dart
> +	Duration bottomBarAnimationDuration = Duration(milliseconds: 400);
Use static const / final for constants

2020-08-29 10:40 UTC, stasgora commented
The PointPickerField widget still uses the CircularProgressIndicator ;)

2020-08-29 13:16 UTC, mikolajmirko commented
I left it there because it's imitates the look of loading SmartSelect. It's grey and small - I tested it and Fokus flower looks not so good in this place (beside the fact I would need to update every SmartSelect with custom builder).

2020-08-29 15:43 UTC, stasgora approved these changes

2020-08-29 15:43 UTC, merged