Feature/fks 102
fokus-team/fokus pull request #34
Opened 2020-08-31 00:55 UTC by Evil00787

Task in progress page with completion, breaks, rejection and completed cards!

2020-08-31 10:24 UTC, stasgora requested changes
Great page <3

2020-08-31 10:24 UTC, stasgora commented on lib/pages/child/plan_in_progress_page.dart
> +								actionButton:	ItemCardActionButton(color: Colors.teal, icon: Icons.play_arrow, onTapped: () => Navigator.of(context).pushNamed(AppPage.childTaskInProgress.name, arguments: task.id)),
Ach, must have forgotten when doing review of this page but as usual you are not using AppColors values. Please check and correct all colors on this page :)

2020-08-31 10:24 UTC, stasgora commented on lib/pages/child/plan_in_progress_page.dart
> +							actionButton:	ItemCardActionButton(color: Colors.teal, icon: Icons.play_arrow, onTapped: () => Navigator.of(context).pushNamed(AppPage.childTaskInProgress.name, arguments: task.id)),
Since this is repeated 3 times you could put this lambda in a variable

2020-08-31 10:24 UTC, stasgora commented on i18n/en_US.json
> +						"content1": "You will receive points after approval by the caregiver.",
approval from

2020-08-31 10:24 UTC, stasgora commented on lib/widgets/cards/sliding_card.dart
> +    								],
You could just do
```suggestion
    								children: this.widget.content,
```

2020-08-31 10:24 UTC, stasgora commented on lib/widgets/task_app_header.dart
> +		return Column(
You could break that method up into at least the actual appBar, timer and button

2020-08-31 10:24 UTC, stasgora commented on lib/pages/child/task_in_progress_page.dart
> +	final GlobalKey<TaskAppHeaderState> header = GlobalKey<TaskAppHeaderState>();
private?

2020-08-31 10:24 UTC, stasgora commented on lib/pages/child/task_in_progress_page.dart
> +  	return Scaffold(
Break this up into logical fragments, it's far to long to be understandable

2020-08-31 10:24 UTC, stasgora commented on lib/pages/child/task_in_progress_page.dart
> +					SlidingCard(
As there are 4 of those cards and they are quite similar you could extract them to function and parameterize the color, animation and content?

2020-08-31 13:08 UTC, Evil00787 commented on i18n/en_US.json
> +						"content1": "You will receive points after approval by the caregiver.",
![image](https://user-images.githubusercontent.com/37753289/91723334-dee18000-eb9b-11ea-98ee-f28e19284e8a.png)

2020-09-06 15:05 UTC, stasgora commented on i18n/en_US.json
> +						"content1": "You will receive points after approval by the caregiver.",
approval -> from
approved -> by
src: https://ell.stackexchange.com/questions/199466/get-approved-from-or-by

2020-09-06 15:31 UTC, stasgora approved these changes

2020-09-06 15:31 UTC, merged