Tasks evaluation
fokus-team/fokus pull request #50
Opened 2020-10-01 23:12 UTC by Evil00787

2020-10-02 19:01 UTC, stasgora requested changes

2020-10-05 14:55 UTC, Evil00787 commented on lib/logic/tasks_evaluation/tasks_evaluation_cubit.dart
> +		int i = _uiTaskInstances.indexOf(_uiTaskInstances.singleWhere((uiTaskInstance) => uiTaskInstance.id == report.task.id));
I initially wanted to update my copy of taskInstances but i realised it was pointless, nvm

2020-10-05 15:10 UTC, Evil00787 commented on lib/widgets/cards/report_card.dart
>                  'POINTS_NUM': (widget.report.ratingMark.value*widget.report.task.points.quantity/5.0).round().toString()
Imo better would be just a simple function in the same file

2020-10-05 17:47 UTC, stasgora commented on lib/widgets/cards/report_card.dart
>                  'POINTS_NUM': (widget.report.ratingMark.value*widget.report.task.points.quantity/5.0).round().toString()
I think you misunderstood. I was talking about only the `(widget.report.ratingMark.value*widget.report.task.points.quantity/5.0).round()` part. That's the logic (small but still). It's repeated in: `TasksEvaluationCubit`, `ReportCard` and `ReportForm`

2020-10-05 18:14 UTC, stasgora commented on lib/widgets/cards/report_card.dart
>                  'POINTS_NUM': (widget.report.ratingMark.value*widget.report.task.points.quantity/5.0).round().toString()
It's actually already incorrect in both ui files as they have no `max(val, 1)` - one more reason to do this :wink:

2020-10-05 18:43 UTC, Evil00787 commented on lib/widgets/cards/report_card.dart
>                  'POINTS_NUM': (widget.report.ratingMark.value*widget.report.task.points.quantity/5.0).round().toString()
ahh, ok

2020-10-05 18:53 UTC, stasgora approved these changes

2020-10-05 18:53 UTC, merged