Added complete Plan button and instant planHeaderWidget update
fokus-team/fokus pull request #60
Opened 2020-10-18 21:06 UTC by Evil00787

now updating plan widget instantly with route
and added complete plan button

2020-10-25 10:06 UTC, stasgora requested changes

2020-10-25 10:06 UTC, stasgora commented on lib/pages/child/task_in_progress_page.dart
> +						Navigator.of(context).pop({"plan" : state is TaskInstanceLoaded ? state.planInstance : null});
Do we need this whole thing? `PlanInstanceCubit` is reloadable so it should update on it's own

2020-10-25 10:06 UTC, stasgora commented on lib/pages/plan/plan_instance_details_page.dart
> +			floatingActionButton: widget.initialPlanInstance.state.ended || _wasPlanCompleted || !widget.showActions || (updatedUiPlanInstance!= null && updatedUiPlanInstance.state.ended) ?
This logic could be done in cubit and returned in state as one bool

2021-01-06 17:30 UTC, Evil00787 commented on lib/logic/common/plan_instance_cubit.dart
> +		emit(ChildTasksLoadSuccess(uiInstances, uiPlanInstance));
Also timer will change... And then it gets complicated imo

2021-01-06 22:53 UTC, stasgora requested changes

2021-01-06 22:53 UTC, stasgora commented on lib/logic/common/plan_instance_cubit.dart
> +		uiPlanInstance = await _dataAggregator.loadPlanInstance(planInstance: planInstance);
It's not going to fetch the fields again unless you only pass it the `planInstanceId` param - so right now the duration should be wrong

2021-01-06 22:53 UTC, stasgora commented on lib/logic/child/task_instance/task_instance_cubit.dart
>  	Task task;
All those should be private

2021-01-06 22:53 UTC, stasgora commented on lib/logic/child/task_instance/task_instance_cubit.dart
> +	UIPlanInstance uiPlanInstance;
This is much better that keeping it in the UI layer but we can do even better. Cubit state is the place to keep all the data, UI should only ever call functions on cubits, not access any of the member fields. You can add a `UIPlanInstance` to `TaskInstanceStateInitial` and access it from there.

2021-01-06 22:53 UTC, stasgora commented on lib/logic/common/plan_instance_cubit.dart
> +	PlanInstanceCubit(this.uiPlanInstance, ModalRoute modalRoute) : super(modalRoute);
In this case it's going to be a little more tricky as I have not yet written any support for custom initial states in reloadable cubits. I will look into this tomorrow

2021-01-07 11:31 UTC, stasgora commented on lib/logic/common/plan_instance_cubit.dart
> +	PlanInstanceCubit(this.uiPlanInstance, ModalRoute modalRoute) : super(modalRoute);
I will leave that case for when I will be properly implementing the page model passing functionality as I see no elegant way of doing it temporarily right now. For now you can leave this cubit as-is.

2021-01-07 18:16 UTC, stasgora commented on lib/logic/child/task_instance/task_instance_cubit.dart
> +	TaskInstanceCubit(this._taskInstanceId, this._activeUser, _uiPlanInstance) : super(TaskInstanceStateInitial(_uiPlanInstance));
No type :wink: 
```suggestion
	TaskInstanceCubit(this._taskInstanceId, this._activeUser, UIPlanInstance _uiPlanInstance) : super(TaskInstanceStateInitial(_uiPlanInstance));
```

2021-01-07 18:30 UTC, stasgora approved these changes

2021-01-07 18:30 UTC, merged